spring:
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data:  classpath:data.sql

  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernte:
        connection:
          charSet: utf-8
        dialect: com.study.www.config.MySQL5DialectUTF8
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy